### ISSUE TITLE
Trj?

### ISSUE THREAD

**Issue by SkylordBrebro** [scorpion3013/SimpleCheck#4]
AVG picked up "Win32:Malware-gen" in the exe. Care to explain?

**Comment by SkylordBrebro** [comment]
Should've read where it was pointing to, my b.

**Comment by noobyme** [comment]
Hi SkylordBreBro I had a similar issue. Can you please explain what you meant by should've read where it pointed to?

**Comment by noobyme** [comment]
https://www.virustotal.com/gui/file/39d95c024447d6a6dcf94cd31f194dd675e20b0601ad6229c66858eceea33bd3/behavior/VirusTotal%20Jujubox
https://www.virustotal.com/gui/file/86020e41e92984e15ffee65c074e9b647f81cf1eac4c288e6d946b53ccf5822a/detection
